### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by aberba** [koldi/webrtc-dlang#1]
Could you show an example of what this package does? Looked thorough the code but it doesn't seem to support WebRTC video/audio stream.

**Comment by koldi** [comment]
Unfortunately it's only a starting project from a few years ago. I wanted to create a full webrtc implementation in D, just for fun but after all I didn't have time for finishing it. :(

**Comment by aberba** [comment]
Oh ok. I'm currently looking for something like that.
